name: inner_speech
channels:
  - conda-forge
dependencies:
  - python>=3.10,<3.13
  - numpy=1.26
  - scipy=1.13
  - pandas=2.2
  - scikit-learn=1.6
  - mne=1.8
  - matplotlib=3.9
  - tensorflow=2.18
  - tensorflow-datasets=4.9
